spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: g&rQ4TS&Xibxo^
    url: jdbc:mariadb://unraid.dsrank.cn:3306/CommunityManagement
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: info
